"$schema" = "../gen/schemas/schema.json"

[[permission]]
identifier = "allow-get-config"
description = "Allows the get_config command"
commands.allow = ["get_config"]

[[permission]]
identifier = "allow-exit-with-code"
description = "Allows the exit_with_code command"
commands.allow = ["exit_with_code"]

[[permission]]
identifier = "allow-resize-window-to-content"
description = "Allows the resize_window_to_content command"
commands.allow = ["resize_window_to_content"]
